# Generated by
# $ ./scripts/build_hash.py 048
# p=lambda g:[[sum(b'AbSE<=`@y2LH9G4l!	\nnTJ"lo2!hKh $`'[(i:=hash((s,*zip(*g)))%336)//7]>>i%7for s in[9,0,6])%2*8]]

# # flood fill through 8s from first 2 block
# # detect connection to another 2 block
# def p(g):
#  w=len(g[0])+2;s=[0]*w
#  for r in g:s+=0,*r,0
#  s+=[0]*w
#  q=[i:=s.index(2),i+1,i+w,i+w+1]
#  for j in q:s[j]=1
#  for i in q:
#   for j in i-1,i+1,i-w,i+w:
#    if 2&s[j]:return(8,),
#    if 8&s[j]:s[j]=1;q+=j,
#  return(0,),

# Generated by ./scripts/build_hash2.py
p=lambda g:[[sum(hash((s,*zip(*g)))*(b"$E8.<%T=NI^rlg'Qa8^n2qT1-	Oq7a- "[s//7]>>s%7)for s in range(273))%2*8]]

